### ISSUE TITLE
Refactor code to improve readability ✨

### ISSUE THREAD

**Issue by jijip41** [fac25/week7-seasonal-calendar#30]
https://github.com/fac25/week7-seasonal-calendar/blob/2f56aa3426380dfc4652c6685945e8c70e2efbce/lib/loadRecipes.js#L23

This is what I meant earlier 😅
It can be like 
```
        return fetch(
            `https://api.edamam.com/api/recipes/v2?type=public&q=${veg}&app_id=b28b6060&app_key=${APIKey}&imageSize=THUMBNAIL&field=label&field=image&field=url&field=ingredientLines&field=totalCO2Emissions`
        )
            .then((res) => res.json())
            .then((recipeArray) => allRecipes.push(recipeArray))
            .catch(console.error)

```
MDN docs here 👇
[Chaining promises](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises#chaining_promises)

**Comment by lisahns** [comment]
thank you @jijip41 :sparkles:
