### ISSUE TITLE
Refactor code x2

### ISSUE THREAD

**Issue by modanova** [fac25/week7-seasonal-calendar#32]
From Team Bookbrooch

Potential for refactoring here. 
![image](https://user-images.githubusercontent.com/99407460/201159787-5ab2fbb7-9526-47f7-81ed-39492f141a62.png)

Suggestion: Loop through all the seasons and create a component for each season. That component takes the months as props.

**Comment by Sumithra-Suresh** [comment]
Refactor example for seasons button :
```
  const seasonBtn = ['Spring', 'Summer', 'Autmun', 'Winter']
  {seasonBtn.map((season, index) => {
      return (
          <button
              className={`${checkActive(
                  index + 1,
                  'opacity-25'
              )}`}
              onClick={() => handleClick(index + 1)}
          >
              {season}
          </button>
      )
  })}
```
