### ISSUE TITLE
I don't know my seasons

### ISSUE THREAD

**Issue by patdel0** [fac25/week7-seasonal-calendar#53]
I'm uneducated and come from a different country, I am unaware when a season starts or ends. 
For other uneducated users like me, would it be possible to have an indication of the end date of the seasons, without having to refer to the other tabs?

![image](https://user-images.githubusercontent.com/53922624/202237249-f3c4d2cb-e485-4598-9e4f-d0116d6a4e76.png)

**Comment by Joe-Lindie** [comment]
Great idea! Unfortunately, we ran out of time. Next time!
