### ISSUE TITLE
Recipes appear with ingredient of same name

### ISSUE THREAD

**Issue by AlexPD93** [fac25/week7-seasonal-calendar#54]
<img width="915" alt="image" src="https://user-images.githubusercontent.com/78558945/202242771-aed8df3d-6f5c-4661-8e52-867f99e29973.png">

The vegetable being displayed is marrow. However the recipe that appears uses bone marrow which is a different ingredient. Is there a way to not allow this to happen?

**Comment by Joe-Lindie** [comment]
The API limits us and we are unable to manipulate the data accurately - Thanks anyway! Paz said sorry for the inconvenience!
