### ISSUE TITLE
Nutritional value

### ISSUE THREAD

**Issue by AlexPD93** [fac25/week7-seasonal-calendar#55]
I really like this addition, it is a nice touch. However, it might be useful to know how much of this vegetable/fruit contains said nutritional value. 

<img width="230" alt="image" src="https://user-images.githubusercontent.com/78558945/202243563-c8721688-a064-4338-b75c-e72305372493.png">

**Comment by Joe-Lindie** [comment]
We'll look later! If we have time. Cheers!
