### ISSUE TITLE
API Key exposed

### ISSUE THREAD

**Issue by patdel0** [fac25/week7-seasonal-calendar#58]
There are bots out there that scrape our repositories for our exposed API Keys and other things. If this were a paid API Key, we'd see a big bill at the end of the month :rofl: 

If we have a look at the Insight tab in the project, we'll see that there's an unusual amount of cloned repositories:
![image](https://user-images.githubusercontent.com/53922624/202247298-6e3181d6-cf1e-4c6d-adf5-ae325116bc4b.png)

Consider using .env files for secret values like an API Key

**Comment by lisahns** [comment]
Thanks Patrick, we didn't know about this!
