### ISSUE TITLE
Possible UX improvement ✨

### ISSUE THREAD

**Issue by jijip41** [fac25/week7-seasonal-calendar#68]
https://github.com/fac25/week7-seasonal-calendar/blob/7a027ffb56438a9a2562162f1c4c72630a47aadc/pages/seasonal-recipes/index.js#L46-L53

I think there is a chance to improve the user experience here. You can make or style this 'search' area to look like a button.

**Comment by Joe-Lindie** [comment]
Thanks! All done!
